spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: rabinpant321@gmail.com
    password: wakjqhkclfysxgoe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true